import {useMemo,useState} from 'react';

const TYPES={plastic:{icon:'🧴',price:18,co2:1.5,tips:'Rinse, dry and remove caps before recycling.'},paper:{icon:'📦',price:10,co2:1.1,tips:'Keep paper clean and dry; flatten cardboard.'},glass:{icon:'🍾',price:3,co2:.7,tips:'Rinse containers and separate by local rules.'},metal:{icon:'🥫',price:45,co2:2.4,tips:'Rinse cans and safely flatten where accepted.'},ewaste:{icon:'🔌',price:80,co2:3.2,tips:'Never mix e-waste with household trash; use an authorised recycler.'}};
const detect=n=>{n=n.toLowerCase();if(/paper|card|box/.test(n))return'paper';if(/glass|bottle/.test(n))return'glass';if(/metal|can|tin|aluminium|steel/.test(n))return'metal';if(/phone|wire|electronic|battery|charger/.test(n))return'ewaste';return'plastic'};

export default function App(){
 const [file,setFile]=useState(null),[result,setResult]=useState(null),[weight,setWeight]=useState(1),[points,setPoints]=useState(120),[history,setHistory]=useState([]),[tab,setTab]=useState('home');
 const preview=useMemo(()=>file?URL.createObjectURL(file):'', [file]);
 function analyze(){if(!file)return;const type=detect(file.name),d=TYPES[type],value=(d.price*weight).toFixed(0),saved=(d.co2*weight).toFixed(1);setResult({type,...d,value,saved});}
 function recycle(){if(!result)return;const earned=Math.max(10,Math.round(weight*20));setPoints(p=>p+earned);setHistory(h=>[{type:result.type,weight,value:result.value,saved:result.saved,date:new Date().toLocaleDateString()},...h]);alert(`Recycling logged! +${earned} Green Points`);}
 return <div><header><div className="brand">🌱 EcoCycle <b>AI</b></div><nav><button onClick={()=>setTab('home')}>Home</button><button onClick={()=>setTab('dashboard')}>Dashboard</button><button onClick={()=>setTab('recyclers')}>Recyclers</button></nav><div className="points">🏆 {points} pts</div></header>
 {tab==='home'&&<main><section className="hero"><span className="pill">AI-powered circular economy</span><h1>Turn waste into <em>value.</em></h1><p>Identify recyclable waste, estimate its value, discover recycling guidance and track your environmental impact.</p><button className="primary" onClick={()=>document.getElementById('upload').scrollIntoView({behavior:'smooth'})}>♻ Start Recycling</button></section>
 <section className="stats"><div><b>6+</b><span>Waste categories</span></div><div><b>₹ Value</b><span>Instant estimate</span></div><div><b>CO₂</b><span>Impact tracking</span></div><div><b>24/7</b><span>Smart guidance</span></div></section>
 <section id="upload" className="panel"><div><span className="eyebrow">SMART SCAN</span><h2>Upload Waste Image</h2><p>Choose a photo of your recyclable item. The MVP classifier provides a category estimate and recycling guidance.</p><label className="drop">{preview?<img src={preview}/>:<><span>📷</span><b>Choose waste image</b><small>JPG, PNG or WEBP</small></>}<input type="file" accept="image/*" onChange={e=>{setFile(e.target.files[0]);setResult(null)}}/></label><div className="weight"><label>Approx. weight (kg)</label><input type="number" min="0.1" step="0.1" value={weight} onChange={e=>setWeight(+e.target.value||.1)}/></div><button className="primary full" disabled={!file} onClick={analyze}>✨ Analyze Waste</button></div>
 <div className="result">{!result?<div className="empty"><span>🤖</span><h3>AI analysis appears here</h3><p>Upload an image to get material type, estimated value and eco impact.</p></div>:<><div className="bigicon">{result.icon}</div><span className="pill">Detected material</span><h2>{result.type.toUpperCase()}</h2><div className="metrics"><div><small>Estimated value</small><b>₹{result.value}</b></div><div><small>CO₂ saved</small><b>{result.saved} kg</b></div></div><div className="tip"><b>♻ Recycling tip</b><p>{result.tips}</p></div><button className="primary full" onClick={recycle}>Log Recycling & Earn Points</button></>}</div></section>
 <h2 className="sectionTitle">Everything you need to recycle smarter</h2><section className="cards">{[['🤖','Waste Detection','Classify common recyclable materials from an uploaded image.'],['💰','Price Estimator','Get an indicative recyclable value based on material and weight.'],['📍','Recycler Finder','Open nearby recycling centres using your current location.'],['🎁','Green Rewards','Earn points when you log recycling activities.'],['🌍','Carbon Savings','Estimate and track CO₂ savings from recycling.'],['📊','Impact Dashboard','View recycling history, rewards and environmental impact.']].map(x=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section></main>}
 {tab==='dashboard'&&<main><section className="pageHead"><span className="eyebrow">YOUR IMPACT</span><h1>Recycling Dashboard</h1></section><section className="dash"><div><small>Green Points</small><b>{points}</b></div><div><small>Items Logged</small><b>{history.length}</b></div><div><small>Total Weight</small><b>{history.reduce((a,x)=>a+x.weight,0).toFixed(1)} kg</b></div><div><small>CO₂ Saved</small><b>{history.reduce((a,x)=>a+Number(x.saved),0).toFixed(1)} kg</b></div></section><section className="panel single"><h2>Recent activity</h2>{history.length?history.map((x,i)=><div className="activity" key={i}><span>{TYPES[x.type].icon}</span><div><b>{x.type}</b><small>{x.date} · {x.weight} kg</small></div><strong>₹{x.value}</strong></div>):<div className="empty"><span>🌿</span><p>Your recycling activity will appear here.</p></div>}</section></main>}
 {tab==='recyclers'&&<main><section className="pageHead"><span className="eyebrow">RECYCLE LOCALLY</span><h1>Find Nearby Recyclers</h1><p>Use Maps to discover recycling centres and scrap dealers around you.</p><a className="primary link" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/recycling+center+near+me">📍 Find on Google Maps</a></section><section className="cards"><article><span>♻️</span><h3>Dry Waste</h3><p>Plastic, paper, cardboard, metal and glass collection.</p></article><article><span>🔌</span><h3>E-Waste</h3><p>Use authorised collection points for electronics and batteries.</p></article><article><span>🤝</span><h3>Donate & Reuse</h3><p>Prefer reuse or donation when an item is still usable.</p></article></section></main>}
 <footer><b>🌱 EcoCycle AI</b><span>Recycle smarter. Reward the planet.</span><small>Indicative estimates only · Hackathon MVP</small></footer></div>
}